//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.TranslatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TranslatorService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLanguages", ReplyAction="http://tempuri.org/IService1/GetLanguagesResponse")]
        string[] GetLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLanguages", ReplyAction="http://tempuri.org/IService1/GetLanguagesResponse")]
        System.Threading.Tasks.Task<string[]> GetLanguagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Translate", ReplyAction="http://tempuri.org/IService1/TranslateResponse")]
        string Translate(string target, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Translate", ReplyAction="http://tempuri.org/IService1/TranslateResponse")]
        System.Threading.Tasks.Task<string> TranslateAsync(string target, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication.TranslatorService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication.TranslatorService.IService1>, WebApplication.TranslatorService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetLanguages() {
            return base.Channel.GetLanguages();
        }
        
        public System.Threading.Tasks.Task<string[]> GetLanguagesAsync() {
            return base.Channel.GetLanguagesAsync();
        }
        
        public string Translate(string target, string body) {
            return base.Channel.Translate(target, body);
        }
        
        public System.Threading.Tasks.Task<string> TranslateAsync(string target, string body) {
            return base.Channel.TranslateAsync(target, body);
        }
    }
}
