//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.WeatherServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherServiceReference.WeatherService")]
    public interface WeatherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeatherService/Weather5Day", ReplyAction="http://tempuri.org/WeatherService/Weather5DayResponse")]
        string[] Weather5Day(string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeatherService/Weather5Day", ReplyAction="http://tempuri.org/WeatherService/Weather5DayResponse")]
        System.Threading.Tasks.Task<string[]> Weather5DayAsync(string zipcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherServiceChannel : TryIt.WeatherServiceReference.WeatherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceClient : System.ServiceModel.ClientBase<TryIt.WeatherServiceReference.WeatherService>, TryIt.WeatherServiceReference.WeatherService {
        
        public WeatherServiceClient() {
        }
        
        public WeatherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Weather5Day(string zipcode) {
            return base.Channel.Weather5Day(zipcode);
        }
        
        public System.Threading.Tasks.Task<string[]> Weather5DayAsync(string zipcode) {
            return base.Channel.Weather5DayAsync(zipcode);
        }
    }
}
